### ISSUE TITLE
Update Crisford to make integration easier

### ISSUE THREAD

**Issue by tobycrisford** [coreycerovsek/wordle-solvers#1]
This looks like a cool project!

The current state of my code makes it difficult to incorporate into a project like this. I'm sorry about that! If you like I can put together a more automatic script with the first guess cached (that's the guess where the brute force approach is really slow).

I have one question though: Are you allowing the solvers to make use of the list of 2,000ish possible solutions from Wordle's source code? I decided not to keep this list separate from the list of valid guesses, and instead assumed every valid guess was also a potential answer, just because that felt like it was more in the spirit of the game. But I know other solvers do use it so can make a version of mine that does too for the purposes of this, if you like?

**Comment by coreycerovsek** [comment]
Thanks Toby! Figuring it out as I go and very open to suggestions! My initial naive thought was that I'd just plug in a bunch of solvers and compare strategies. I quickly discovered how many solvers use incompatible dictionaries or simply fail due to bugs! At first I started fixing bugs and replacing dictionaries. Then I realized this wasn't scalable — for comparing strategies, it will be easier just to reimplement them — and so this turned instead into a little meditation on the reliability of code posted online and the subtleties of measurement. The revised goal is to quantify how posted solvers would perform for a user applying them "as is" to the "real" Wordle app.

After which I do still intend to measure strategies as originally intended. 😭

Anyway! For now for expediency my aim is to be non-invasive except as absolutely necessary for code reuse. Since some solvers do incorporate (and distinguish) the "solution" and "legal guess" dictionaries, by the non-invasive principle, that's legit. (And obviously beneficial.) (My evaluation doesn't currently check whether guesses are legal; I don't think anyone is "abusing" that with synthetic words, and one solver even accepts feedback indicating a guess is invalid, but I really should check guesses for acceptability too and fail solver runs that don't provide alternatives. To do.) I'm using a 2013 MacBook not intended for space heating so I'm frugal with variants, but happy to include some as you can see with Olson. Given your two boolean switches, I didn't yet read carefully enough to clarify whether there are three or four variants, but if you're game to indicate a principal variant, and/or optimize by pre-evaluating first guesses as well that would be great! Happy to run a handful of variants too, if you specify CLI inputs. Also happy to pull changes from your repo or to take pull requests.

In a better world the solvers would perform "undo" on appropriate sentinel feedback so I wouldn't repeatedly calculate so many initial states. But I can't fork processes externally and CRIU seems way off-topic, so for now I'm just putting up with the inefficiency. Partial evaluation is highly welcome!

By the way, I appreciate what you wrote re. word frequencies and realism. Philosophically solid points.

**Comment by tobycrisford** [comment]
Thanks for getting back! It's certainly an interesting project you've taken on, and I'm flattered you've included mine in the list.

I've put together a version which should be a bit easier for you to incorporate (and which makes use of the separate solution list as well).

It's currently in a separate script in a separate branch, here: https://github.com/tobycrisford/wordle_solver/blob/wordle_solver_corey/wordle_solver_corey.py

You can pull it into your fork, or you could literally just copy+paste that short script into the directory and it should be runnable when combined with the stuff you've already got.

The first guess is now hard coded, which should make it a lot faster (especially as size of the solution list has shrunk too) and there's no boolean flags to select. I reckon this version will perform close to optimally, although I've seen at least one person who has fully solved the game, and my turn-at-a-time approach won't be able to compete with that!

**Comment by coreycerovsek** [comment]
Thanks! Merged the branch, was able to simplify the "driver" and the program's churning now. It looks like it will take 3-4 hours to run through the list on four logical cores. Ah, Python showing its cost. But I'm caching played games, so once it's done I can send you the static game tree if you'd like it.

Have you found anyone who has claimed to find a truly optimal strategy? [Jonathan Olson](https://jonathanolson.net/experiments/optimal-wordle-solutions) posted the nicest discussion I've seen of how greedy strategies are not necessarily optimal. He's gotten his average guesses down to ~3.42 with one strategy and says another is 18 cases short of solving any word with at most four guesses. (His code in here includes eight precomputed game trees that I've hooked up as solvers.) I don't have a clear sense of the computational complexity of finding and proving that one has an optimal game tree, though. What do you think: tractable or untractable?

**Comment by coreycerovsek** [comment]
"Crisford" solver averages 3.4639 guesses! Amongst the ones I've integrated, it's only beaten by the "Olson Total" solvers, all in the 3.42-3.43 range. The other two without bugs or incompatible dictionaries, "Kerrigan"  averages 3.7598 and "Christensen" averages 3.6406.

**Comment by tobycrisford** [comment]
Alex Selby claimed here to have proven that he has the optimum game tree: https://twitter.com/alexselby1770/status/1484241692102385668

And the write-up looks good to me! Given how long it takes my code just to compute the first guess, I'm seriously impressed with this approach.

He claims a performance of 3.4212, so that would then be a hard upper bound on Wordle performance. That seems to tie in nicely with the best score you've seen so far.

Thank you for doing the hard work of testing mine for me. I'm pleased with how close it gets to that limit!

Although the adjustment I was really proud of was taking into account word frequencies, which only helps if you say you're now allowed to just extract the solution list from the game.

**Comment by coreycerovsek** [comment]
Beautiful! That’s just what I was hoping for, and right as I was about to take my C++ sledgehammer to this. Looking forward to reading the code!
